### ISSUE TITLE
LGPL3 license makes this practically un-usable

### ISSUE THREAD

**Issue by hsson** [GrenderG/MarkdownView#1]
Would have loved to use this great library, but since it's licensed under LGPL 3.0 it is impossible for us to use it as we cannot comply with the disclosure of source code condition.

**Comment by GrenderG** [comment]
Since this license was not intended to be used in Android libraries there won't be any issues as long as you do [this](https://stackoverflow.com/a/27616714/4208583). You can search a bit and you'll notice that LGPL 3.0 kind of falls in a "legal void" when used in Android libraries. :stuck_out_tongue_closed_eyes: 

Basically, these three will work for me:
- Don't obfuscate the library.
- Don't make any check to see if the library has been changed / edited.
- If you make any changes to the library, create a PR or an open fork.

I created [Libcense](https://github.com/GrenderG/Libcense-1.0) some time ago to solve issues like this, but I never used it.
